services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: billeasy
      POSTGRES_USER: billeasy
      POSTGRES_DB: billeasy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cache:
    image: redis
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379

volumes:
  pgdata:
  cache:
